# XBalanseBot/render.yaml - Чертеж для развертывания XBalanseBot на Render.com
# https://render.com/docs/blueprint-spec

# Сначала определяем все базы данных, которые нам нужны.
databases:
  - name: xbbot-db      # Имя, по которому мы будем обращаться к базе внутри этого файла.
    region: frankfurt
    plan: free         # Тарифный план.

# Затем определяем все наши сервисы (приложения, воркеры и т.д.).
services:
  # Наш единственный сервис - это веб-сервер для бота.
  - type: web
    name: xbalansebot-app # Имя сервиса. Оно станет частью публичного URL.
    runtime: python
    region: frankfurt
    branch: master       # Ветка в Git, за которой нужно следить.
    plan: free

    # Команды для сборки и запуска проекта.
    buildCommand: "poetry install --no-root --without dev"
    startCommand: "poetry run python main.py"

    # Переменные окружения для этого сервиса.
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: DEV_MODE
        value: False
      - key: DATABASE_URL
        # Берем строку подключения из базы данных 'xbbot-db', определенной выше.
        fromDatabase:
          name: xbbot-db
          property: connectionString
      - key: WEBHOOK_HOST
        # Берем автоматически сгенерированное имя хоста для этого сервиса.
        # Это самый правильный способ получить URL.
        fromService:
          type: web
          name: xbalansebot-app
          property: host