# XBalanseBot/render.yaml
# v1.3.2 - 2025-08-20 (Corrected YAML syntax based on official documentation)
# 2025-08-20 20:45:00
# https://render.com/docs/blueprint-spec

databases:
  - name: xbbot-db
    region: frankfurt
    plan: free

# --- ГРУППА ПЕРЕМЕННЫХ ОКРУЖЕНИЯ ---
envVarGroups:
  - name: xbalansebot-secrets
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAIN_GROUP_ID
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: TRIBUTE_WEBHOOK_SECRET
        sync: false


services:
  # Основной сервис для ответов бота
  - type: web
    name: xbalansebot-app
    runtime: python
    region: frankfurt
    branch: master
    plan: free
    rootDir: .
    buildCommand: "poetry install --no-root --without dev"
    startCommand: ".venv/bin/python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: POETRY_VERSION
        value: 2.1.3
      - key: DEV_MODE
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: xbbot-db
          property: connectionString
      - key: WEBHOOK_HOST
        value: xbalansebot-app.onrender.com
        
 